[package]
name = "ragdoll"
version = "0.1.0"
authors = ["Eric Wei <786655727@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
